### ISSUE TITLE
Please, add parentheses after each function in pipe

### ISSUE THREAD

**Issue by GegznaV** [MaximeWack/desctable#13]
I want to congratulate you on a nice work of creating this package. I'd like to include it in my teaching, as it is tidyverse-compatible. I have one question: is there any reason, why you do not follow the tidyverse style guide in your examples? In particular, I mean this idea: https://style.tidyverse.org/pipes.html#no-arguments, e.g.:
![image](https://user-images.githubusercontent.com/12725868/52519827-fa0f3680-2c69-11e9-90fd-a9dc7d947092.png)

**Is there any chance the parentheses appear after each function in your code examples?** It would be less confusing for new users. Especially as RStudio highlights functions with parentheses in a different color:

![image](https://user-images.githubusercontent.com/12725868/52519838-40fd2c00-2c6a-11e9-9a50-5e45595e8ce1.png)
vs.
![image](https://user-images.githubusercontent.com/12725868/52519840-4f4b4800-2c6a-11e9-9b5a-ff72a85db1d8.png)

On the other hand, alignment at `=` is an excellent idea and makes the code more readable. Please, keep it in all the examples.

![image](https://user-images.githubusercontent.com/12725868/52519889-05169680-2c6b-11e9-87f4-4d58518d8cfb.png)

**Comment by MaximeWack** [comment]
Hi,

Thanks for the suggestions.
The changes have been included in the code with https://github.com/MaximeWack/desctable/pull/16
