### ISSUE TITLE
Similar failure to #2 and #3 when "install_github(..., build_vignette=T)"

### ISSUE THREAD

**Issue by BetweenTwoTests** [MaximeWack/desctable#4]
Similar to  #2 #3 

Installed pander & webshot but the same error (without any details)

`devtools::install_github("maximewack/desctable", build_vignettes = T)` does not work but `devtools::install_github("maximewack/desctable")` work fine. I believe the error is from the vigentte building process. I don't use markdown on my machine, so this might be the issue? I installed `library(rmarkdown)` but the error persists. I am going to guess that because I don't have TeX installed on my machine, the "buid_vignette" process is failing. Perhaps the readme should suggest installing without building vignette.

`
devtools::install_github("maximewack/desctable", build_vignettes = T)
Downloading GitHub repo maximewack/desctable@master
from URL https://api.github.com/repos/maximewack/desctable/zipball/master
Installing desctable
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  "C:\Users\Leon\AppData\Local\Temp\RtmpEFpbJ0\devtoolsc8c4218cd\MaximeWack-desctable-7299652" --no-resave-data --no-manual 

* checking for file 'C:\Users\Leon\AppData\Local\Temp\RtmpEFpbJ0\devtoolsc8c4218cd\MaximeWack-desctable-7299652/DESCRIPTION' ... OK
* preparing 'desctable':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR

Attaching package: 'desctable'

The following object is masked from 'package:DT':

    datatable

The following objects are masked from 'package:stats':

    IQR, chisq.test, fisher.test

Error in value[[3L]] : subscript out of bounds
Calls: <Anonymous> -> tryCatch -> tryCatchList -> tryCatchOne
Execution halted
Error: Command failed (1)
`

**Comment by MaximeWack** [comment]
Thanks for reporting this!

This looks like it is windows specific (`devtools::build_win()` returns the same error).  
I'll investigate this further.

For now, installing with `devtools::install_github("maximewack/desctable")` is ok, as the pre-built vignette seems to work fine.  
I've updated the README to reflect that.

**Comment by MaximeWack** [comment]
Ok, caught a problem with unicode non-breakable spaces on windows. This has fixed the vignette building issue. (you still need to call `devtools::install_github` with `build_vignettes = T` and `force = T` a couple times to actually build the vignette if all required packages are not yet installed)
