### ISSUE TITLE
Small typo: "adress"

### ISSUE THREAD

**Issue by RaoOfPhysics** [MaximeWack/desctable#5]
In three places in this repo ([[1]](https://github.com/MaximeWack/desctable/blob/edd4e4de1c5223ce4741b3efa0022363c1041973/README.Rmd), [[2]](https://github.com/MaximeWack/desctable/blob/a048886d5b95de0ed7701822b752a4e8c83df989/vignettes/desctable.Rmd), [[3]](https://github.com/MaximeWack/desctable/blob/edd4e4de1c5223ce4741b3efa0022363c1041973/README.md)), "address" is misspelt as "adress".

**Comment by MaximeWack** [comment]
Thanks!

Fixed in https://github.com/MaximeWack/desctable/commit/89514b83ba21785ef7832aa2534b54b5aa10c1bf and https://github.com/MaximeWack/desctable/commit/e00fad25246f6113ffc8c43ab0f79a0d33b12f6e
