### ISSUE TITLE
Character

### ISSUE THREAD

**Issue by fabach** [MaximeWack/desctable#6]
Hi, 
In descTable() function it's impossible for me to get character. Is it normal? How can we do it? 

  _BDD %>% select_(.dots=variableetude)%>%  desctable(
stats = list("Total" = function(x) if(is.numeric(x)){paste(round(mean(x),2)," (",sd(x),")",sep="")
                                    }else if(is.logical(x)){round(mean(x)*100,2)
                                    }else{round(percent(x),2)}
     ))_
               
      Thank you for answer
Thibaut FABACHER

**Comment by MaximeWack** [comment]
Hi,

This is intended, for numerous reasons:
- the resulting table needs to be *tidy* (ie: one data point per cell)
- to prevent numerical values from being treated as characters (so as to preserve the ability to sort, filter, or do computations on those numerical values)
- content should be distinct from form.

I've been considering enabling this for purely textual columns, and is a change that should come with version 0.2.0 though. You'll be able to do such things in the next release.

In the meanwhile, I'd advise to prepare data first (transform logicals into factors), generate all the needed statistics in their own column then merge the columns as you see fit for presentation.

Using the development version (`devtools::install_github("maximewack/desctable", ref = "dev")`), try this:

```{r}
BDD %>%
# transform all logicals into factors (there needs to be some logicals in the dataframe)
  dplyr::mutate_if(is.logical,
                   factor,
                   levels = c(F, T),
                   labels = c("No", "Yes"))
# generate the needed statistics
  desctable(stats = list("mean_p" = is.factor ~ percent | mean,
                         "sd" = is.factor ~ NA | sd)) %>%
# coerce to data.frame
  as.data.frame %>%
# create the combined variable with formatting
  dplyr::mutate(Total = ifelse(!is.na(sd), stringr::str_c(round(mean_p, 2), " (", round(sd, 2), ")"), round(mean_p, 2))) %>%
  dplyr::select(-mean_p, -sd)
```

**Comment by fabach** [comment]
Thank you, 
I didn't think to transforme my data.frame after

**Comment by MaximeWack** [comment]
In the latest dev version, what you tried to do in the first place will work as-is.  
It is still not recommended to do it that way, but it is possible now.
