### ISSUE TITLE
How to exclude tests from output?

### ISSUE THREAD

**Issue by ghost** [MaximeWack/desctable#7]
I found this package very helpful for producing descriptive statistics. 
In the following example, however, I would like to exclude tests from output.
I tried using `tests=NULL` but returns an error. 

```
mtcars %>%
  dplyr::mutate(am = factor(am, labels = c("Automatic", "Manual"))) %>%
  group_by(am) %>%
  desctable %>%
  datatable
```

**Comment by MaximeWack** [comment]
Try

```
mtcars %>%
  group_by(am) %>%
  desctable(tests = list(.default = ~no.test))
```

This will output `NA` for p values, and `no.test` for the chosen test, but the columns will still be there.

However, you can manipulate the resulting object from `desctable` to get rid of the tests altogether:

```
mtcars %>%
  group_by(am) %>%
  desctable %>% # the output from desctable is actually a list of dataframes : one for variable names, one for each group, one for the tests
  .[-length(res)] %>% # this line deletes the last dataframe in the list, i.e the one with the tests
  `class<-`("desctable") %>% # this line gives back the "desctable" class to the object, needed for the output
  datatable
```

**Comment by ghost** [comment]
Thanks a lot. I did something like the 2nd one but missed the `class` assignment. 
Μy humble opinion is that it should be easier for the user to get rid of the tests altogether (i.e. using tests=NULL).

**Comment by MaximeWack** [comment]
Unclosing this as a feature request

**Comment by desctable** [comment]
The new `desc_table` API makes it the default to create a table without tests.  
Tests are added using `desc_tests`.
