### ISSUE TITLE
Use !! instead of eval() for unquoting

### ISSUE THREAD

**Issue by krlmlr** [MaximeWack/desctable#8]
The upcoming release of *dplyr* is using *tidyselect*, which doesn't currently support `eval()` inside `select()` (https://github.com/tidyverse/tidyselect/issues/54). Can you try using `!!` instead of `eval()` in `subTable()` (and perhaps elsewhere), please?

We're planning to submit a dplyr update in March.

**Comment by MaximeWack** [comment]
Thanks for the heads up!

Fixed in the `dev` branch @ 1292d913f0af6faf43099f7d000aeaca40226034. I'll merge this in `master` ASAP.
