### ISSUE TITLE
Rounding of Numbers in desctable

### ISSUE THREAD

**Issue by Spatial-R** [MaximeWack/desctable#9]
Hello, thanks for your package. When i used the desctable package to create the descriptive table in a word file, but i can't control the rounding of number. Any solution to this problem? Thanks again.

**Comment by MaximeWack** [comment]
Hi!

You can control the rounding of numbers through the options corresponding to the output type you want to use:
- dataframe : use `options(digits = 4)`
- pander : use the *digits* option of the `pander` call (`mtcars %>% desctable %>% pander(digits = 4)`)
- DT : use the *digits* option of the `datatable` call (`mtcars %>% desctable %>% datatable(digits = 4)`)
